### ISSUE TITLE
fs related tests sometimes fail

### ISSUE THREAD

**Issue by oliversalzburg** [apache/cordova-lib#700]
Whenever I run the test suite of this module, I see random failures relating to `somedir`:
```shell
1) util module isCordova method Test 001 : should return false if it hits the home directory
  Message:
    Error: EPERM: operation not permitted, mkdir 'C:\Users\Oliver\somedir'
  Stack:
    error properties: Object({ errno: -4048, code: 'EPERM', syscall: 'mkdir', path: 'C:\Users\Oliver\somedir' })
    Error: EPERM: operation not permitted, mkdir 'C:\Users\Oliver\somedir'
        at Object.fs.mkdirSync (fs.js:885:18)
        at Object.mkdirsSync (P:\cordova-cross-spawn-test\cordova-lib\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:31:9)
        at UserContext.<anonymous> (P:\cordova-cross-spawn-test\cordova-lib\spec\cordova\util.spec.js:43:16)
        at <Jasmine>
        at runCallback (timers.js:789:20)
```

I believe that this behavior is specific to Windows and happens when the directory is created and deleted repeatedly.

**Comment by oliversalzburg** [comment]
Seems like this is also fixed by #705. The entire test suite passes fine with that patch.
