### ISSUE TITLE
add and run platform commands 

### ISSUE THREAD

**Issue by jbdoster** [apache/cordova-lib#753]
### Issue Type
- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description
1. Trying to use "ionic cordova run ios" and receiving error 
2. Trying to use "ionic cordova platform add ios" and receiving error

## Information
1. Error received:
```
> cordova platform add ios --save
Using cordova-fetch for cordova-ios@^5.0.0
Adding ios project...
Creating Cordova project for the iOS platform:
        Path: platforms/ios
        Package: com.jft.whiskerpaws
        Name: Whisker+Paw
iOS project created with cordova-ios@5.0.0
Cannot find plugin.xml for plugin "cordova-plugin-add-swift-support". Please try adding it again.
[ERROR] An error occurred while running subprocess cordova.
        
        cordova platform add ios --save exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
```

Is this because of this [commit](https://github.com/apache/cordova-lib/commit/8371d7c1bca6b4ca6e64055054405edf8ccf11b6)?

2. Error received:
```
Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-filepicker on ios platform only.
No scripts found for hook "before_plugin_install".
Install start for "cordova-plugin-filepicker" on ios.
Beginning processing of action stack for ios project...
Action stack processing complete.
pods.json found in platforms/ios
Podfile found in platforms/ios
Install complete for cordova-plugin-filepicker on ios.
Finding scripts for "after_plugin_install" hook from plugin cordova-plugin-filepicker on ios platform only.
Executing script found in plugin cordova-plugin-filepicker for hook "after_plugin_install": plugins/cordova-plugin-filepicker/src/ios/hooks/install_entitlements.js
Running hook to add iCloud entitlements
Failed to install 'cordova-plugin-filepicker': CordovaError: Using "requireCordovaModule" to load non-cordova module "xcode" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/Users/dev/.npm-global/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at module.exports (/Users/dev/Documents/w+p/whisker-paw-mobile/plugins/cordova-plugin-filepicker/src/ios/hooks/install_entitlements.js:8:23)
    at runScriptViaModuleLoader (/Users/dev/.npm-global/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
    at runScript (/Users/dev/.npm-global/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
    at /Users/dev/.npm-global/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
CordovaError: Using "requireCordovaModule" to load non-cordova module "xcode" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/Users/dev/.npm-global/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at module.exports (/Users/dev/Documents/w+p/whisker-paw-mobile/plugins/cordova-plugin-filepicker/src/ios/hooks/install_entitlements.js:8:23)
    at runScriptViaModuleLoader (/Users/dev/.npm-global/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
    at runScript (/Users/dev/.npm-global/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
    at /Users/dev/.npm-global/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
Using "requireCordovaModule" to load non-cordova module "xcode" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
[ERROR] An error occurred while running subprocess cordova.
        
        cordova platform add ios --verbose --save exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: process.exit received +0ms
  ionic:utils-process onBeforeExit handler: running 1 functions +0ms
  ionic:utils-process onBeforeExit handler: exiting (exit code 1) +148ms
```

### Command or Code
1. ionic cordova run ios
2. ionic cordova platform add ios

### Environment, Platform, Device
macOS High Sierra
Version 10.13.6
Processor 2.2 GHz Intel Core i7

### Version information
Full output from command cordova info [here](https://github.com/jbdoster/cordova-info/blob/master/output)

## Checklist
- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
The problem is that cordova-plugin-filepicker is not compatible with the latest version of Cordova.

The error message is shown here:
```Failed to install 'cordova-plugin-filepicker': CordovaError: Using "requireCordovaModule" to load non-cordova module "xcode" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.```

You should report this on the cordova-plugin-filepicker repo.
