### ISSUE TITLE
App Preferences Plugin Install Error

### ISSUE THREAD

**Issue by LucaFeger** [apache/cordova-lib#776]
When installing the app-preferences plugin the following error occures:

> Installing "cordova-plugin-app-preferences" for android
Failed to install 'cordova-plugin-app-preferences': CordovaError: Using "requireCordovaModule" to load non-cordova module "path" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (C:\Users\Megapoort\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\Context.js:57:15)
    at module.exports (P:\Projektkurs\Vertretungsplan\plugins\cordova-plugin-app-preferences\bin\before_plugin_install.js:6:14)
    at runScriptViaModuleLoader (C:\Users\Megapoort\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:181:32)
    at runScript (C:\Users\Megapoort\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:157:16)
    at C:\Users\Megapoort\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:125:20
    at <anonymous>
Using "requireCordovaModule" to load non-cordova module "path" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at process._tickCallback (internal/process/next_tick.js:160:7)

The error occured after using the command `ionic cordova plugin add cordova-plugin-app-preferences`

I've tested it out on Windows and Linux. The plattform was android both times.
Cordova and all other dependencies are up2date, so Cordova is on version 9.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by LucaFeger** [comment]
Seems to be an error of the plugin, which wasn't updatet for 2 years, so it isn't compatible to cordova 9.
I've downgraded again and now it works.
