### ISSUE TITLE
Doesn't raise exit error code when hook executing failed

### ISSUE THREAD

**Issue by testerman77** [apache/cordova-lib#792]
# Bug Report

### What is expected to happen?
Exit with error code

### What does actually happen?
Just exit without error code

## Information
I was building an app in Jenkins. When executing hook, it raised an error for 'Can't find module xxx', and then exit.

The Jenkins assert the build success for without nonzero exit code.

Error log:
```
Executing script found in config.xml for hook "before_compile": scripts/remove_redundant_permissions.js
Cannot find module '/xx/common-android'
Error: Cannot find module '/xx/plugins/xx/scripts/common-android'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at module.exports (/xx/scripts/remove_redundant_permissions.js:15:16)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
clear android www content...
zip android www content finish...
```

### Version information

Mac osx 10.14.4

node v10.15.3

Cordova 9.0.0

Cordova-lib 9.0.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by raphinesse** [comment]
Hi, can you please provide exact steps to reproduce the problem? I tried the following but `cordova` _did_ exit with error code 1 as expected:

```
cordova create app && cd app
cordova platform add browser
echo "throw new Error('XXX')" > error.js
sed -i '/<\/widget>/i\    <hook type="before_compile" src="error.js" />' config.xml
cordova compile
```

In the meantime I'm going to close this issue. If you help us to reproduce it, I will re-open it.
