### ISSUE TITLE
NodeJS14: Warning: Accessing non-existent property 'android'

### ISSUE THREAD

**Issue by breautek** [apache/cordova-lib#834]
# Bug Report

## Problem
`cordova platform add android` produces a warning

### What is expected to happen?
No warnings produced

### What does actually happen?
```
(node:11565) Warning: Accessing non-existent property 'android' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```

## Information

NodeJS 14
Ubuntu 18
Cordova 9/ cordova-lib@9.0.1

`node --trace-warnings` produces:

```
(node:11647) Warning: Accessing non-existent property 'android' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Object.hostSupports (/home/norman/.nvm/versions/node/v14.2.0/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js:83:22)
    at addHelper (/home/norman/.nvm/versions/node/v14.2.0/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/platform/addHelper.js:47:27)
    at Function.add (/home/norman/.nvm/versions/node/v14.2.0/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/platform/index.js:27:12)
    at /home/norman/.nvm/versions/node/v14.2.0/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/platform/index.js:71:35
```
Low priority as it is just a warning, and the command still appears to work. But I think we should still look into why the warning is being produced to begin with.

This only occurs on the NodeJS 14.

### Command or Code

`cordova platform add android` on a newly created project.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Same thing also happens on `cordova platform ls`, which produces:

```
norman@norman-ThinkPad:/development/totalpave/tp-iri-client$ cordova platform ls
Installed platforms:
  android 8.1.0
Available platforms: 
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0
(node:13203) Warning: Accessing non-existent property 'ios' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13203) Warning: Accessing non-existent property 'osx' of module exports inside circular dependency
(node:13203) Warning: Accessing non-existent property 'android' of module exports inside circular dependency
(node:13203) Warning: Accessing non-existent property 'windows' of module exports inside circular dependency
(node:13203) Warning: Accessing non-existent property 'browser' of module exports inside circular dependency
(node:13203) Warning: Accessing non-existent property 'electron' of module exports inside circular dependency
```

**Comment by bouraqadi** [comment]
Same on mac os.

**Comment by breautek** [comment]
Closing this as it doesn't reproduce on nightly.
